# Generated by Django 2.0.2 on 2019-05-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20190514_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='important',
            new_name='imp',
        ),
    ]
