# Generated by Django 2.0.2 on 2019-05-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20190514_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_name',
            field=models.TextField(),
        ),
    ]
