# Generated by Django 2.0.2 on 2019-05-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20190514_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word_name',
            new_name='word_num',
        ),
    ]
