# Generated by Django 2.0.2 on 2019-05-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20190514_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='imp',
        ),
    ]
