# Generated by Django 2.0.2 on 2019-05-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_remove_word_imp'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='imp',
            field=models.IntegerField(default=1),
        ),
    ]
